contentColumnType: string(255)
fieldGroup: f1759689-b13f-4dce-9237-dc239d851a44
handle: socialYoutube
instructions: ''
name: 'Social Youtube'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
